CREATE TABLE [dbo].[Specifications]
(
	[sId] INT NOT NULL PRIMARY KEY,
	[sName] VARCHAR(MAX) NOT NULL,
	[sDesc] VARCHAR(MAX) NULL,
	[pId] INT NOT NULL FOREIGN KEY REFERENCES Projects(pId) ON DELETE NO ACTION
)
