CREATE TABLE [dbo].[Teams]
(
	[tId] INT NOT NULL PRIMARY KEY IDENTITY(0,1),
	[tName] VARCHAR(MAX) NOT NULL,
	[tDesc] VARCHAR(MAX) NULL,
	[tLeader] INT NULL FOREIGN KEY REFERENCES Employees(eId) ON DELETE SET NULL
)
