CREATE TABLE [dbo].[Versions]
(
	[vId] INT NOT NULL PRIMARY KEY IDENTITY(0,1),
	[pId] INT NOT NULL FOREIGN KEY REFERENCES Projects(pId) ON DELETE NO ACTION,
	[vNum] INT NOT NULL,
	[ReleaseDate] DATE NOT NULL DEFAULT(GETDATE()),
	UNIQUE (pId, vNum)
)
