CREATE TABLE [dbo].[ProjectClients]
(
	[pId] INT NOT NULL FOREIGN KEY REFERENCES Projects(pId) ON DELETE CASCADE,
	[cId] INT NOT NULL FOREIGN KEY REFERENCES Clients(cId) ON DELETE CASCADE,
	PRIMARY KEY (pId, cId)
)
