CREATE TABLE [dbo].[ProjectClients]
(
	[pId] INT NOT NULL FOREIGN KEY REFERENCES Projects(pId) ON DELETE NO ACTION,
	[cId] INT NOT NULL FOREIGN KEY REFERENCES Clients(cId) ON DELETE NO ACTION,
	PRIMARY KEY (pId, cId)
)
