CREATE TABLE [dbo].[TeamMembers]
(
	[eId] INT NOT NULL FOREIGN KEY REFERENCES Employees(eId) ON DELETE CASCADE,
	[tId] INT NOT NULL FOREIGN KEY REFERENCES Teams(tId) ON DELETE CASCADE,
	PRIMARY KEY (eId, tId)
)
