CREATE TABLE [dbo].[VersionSpecs]
(
	[vId] INT NOT NULL FOREIGN KEY REFERENCES Versions(vId) ON DELETE NO ACTION,
	[sId] INT NOT NULL FOREIGN KEY REFERENCES Specifications(sId) ON DELETE NO ACTION,
	PRIMARY KEY (vId, sId)
)
