CREATE TABLE [dbo].[VersionTeams]
(
	[tId] INT NOT NULL FOREIGN KEY REFERENCES Employees(eId) ON DELETE NO ACTION,
	[vId] INT NOT NULL FOREIGN KEY REFERENCES Versions(vId) ON DELETE NO ACTION,
	PRIMARY KEY (tId, vId)
)
